from labs.clients.factory import *
from labs.clients.impl.gemini import GeminiClient


def test_get_list_of_available_model():
    assert len(get_list_of_available_model()) > 0


def test_client_factory():
    client = ClientFactory.get_client(model_name="gemini-1.5-flash-002")
    assert isinstance(client, GeminiClient)

    # test the runnable of the client after being generated by client factory
    response = client.chat("hello?")
    assert response.content != None